-- Migration generated by Drismify
-- Migration name: create_user_table

BEGIN;

-- Create User table
CREATE TABLE "user" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TEXT NOT NULL
);

-- Create index for email
CREATE UNIQUE INDEX "idx_user_email" ON "user" ("email");

COMMIT;
